from project.com.controller import HomeController
from project.com.controller import CatalogController
from project.com.controller import MajorController
from project.com.controller import CourseController
from project.com.controller import RegisteredUserController
from project.com.controller import UnregisteredUserController
from project.com.controller import UserController
from project.com.controller import LoginController
from project.com.controller import MessageController
from project.com.controller import TutorPostingController
